{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import shutil\n",
    "import sys\n",
    "sys.path.append('../datapipeline')\n",
    "sys.path.append('../imgclsmob/tensorflow2')\n",
    "sys.path.append('../akhelpers')\n",
    "\n",
    "\n",
    "import autokeras as ak\n",
    "from Common_AK import CustomGlobalPool\n",
    "from Resnet_AK import CustomResnetBlock\n",
    "\n",
    "from DatagenClassification import TFClassificationDataGenerator\n",
    "import random\n",
    "random.seed(47)\n",
    "import albumentations as A\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "from kerastuner.engine.hyperparameters import HyperParameters\n",
    "\n",
    "from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "IMAGE_SIZE = (None, None)\n",
    "NUM_CHANNELS = (3,)\n",
    "NUM_CLASSES = 3\n",
    "MAX_NETWORK_SEARCH_TRIALS = 500\n",
    "BATCH_SIZE = 1\n",
    "VAL_DS_SIZE = 2058\n",
    "TRAIN_DS_SIZE = 4464\n",
    "EPOCHS = 10\n",
    "MODEL_DIR = 'auto_model'\n",
    "PROJECT_NAME = 'resnet_ak'\n",
    "OVERITE_PROJECT = False\n",
    "\n",
    "train_files = ['../../../data/coco_person_classification_tiny/train_class-00000-of-00005', \n",
    "               '../../../data/coco_person_classification_tiny/train_class-00001-of-00005', \n",
    "               '../../../data/coco_person_classification_tiny/train_class-00002-of-00005', \n",
    "               '../../../data/coco_person_classification_tiny/train_class-00003-of-00005', \n",
    "               '../../../data/coco_person_classification_tiny/train_class-00004-of-00005']\n",
    "val_files = ['../../../data/coco_person_classification_tiny/val_class-00000-of-00005', \n",
    "             '../../../data/coco_person_classification_tiny/val_class-00001-of-00005', \n",
    "             '../../../data/coco_person_classification_tiny/val_class-00002-of-00005', \n",
    "             '../../../data/coco_person_classification_tiny/val_class-00003-of-00005', \n",
    "             '../../../data/coco_person_classification_tiny/val_class-00004-of-00005']\n",
    "has_bg = True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'adam'"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# restric the search space\n",
    "hp = HyperParameters()\n",
    "hp.Choice(\n",
    "            \"optimizer\",\n",
    "            [\"adam\", \"sgd\"],\n",
    "            default=\"adam\",\n",
    "        )\n",
    "# hp.Fixed(\n",
    "#             \"optimizer\",\n",
    "#             \"sgd\"\n",
    "#         )"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Define Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "input_node = ak.Input()\n",
    "output_node = ak.ImageAugmentation(\n",
    "    translation_factor=0.2,\n",
    "    vertical_flip=True,\n",
    "    horizontal_flip=True,\n",
    "    rotation_factor=1.0,\n",
    "    zoom_factor=0.2,\n",
    "    contrast_factor=0.2\n",
    ")(input_node)\n",
    "output_node = ak.Normalization()(output_node)\n",
    "output_node = CustomResnetBlock(in_size=IMAGE_SIZE)(output_node)\n",
    "output_node = CustomGlobalPool()(output_node)\n",
    "output_node = ak.ClassificationHead(num_classes=NUM_CLASSES, multi_label=True)(output_node)\n",
    "auto_model = ak.AutoModel(\n",
    "    inputs=input_node, \n",
    "    outputs=output_node,\n",
    "    overwrite=OVERITE_PROJECT,\n",
    "    directory=MODEL_DIR,\n",
    "    max_trials=MAX_NETWORK_SEARCH_TRIALS,\n",
    "    hyperparameters=hp,\n",
    "    project_name=PROJECT_NAME)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Define Image Preprocessing "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "train_transform = A.Compose([\n",
    "        A.Rotate(limit=180),\n",
    "        A.Flip(),\n",
    "        A.Transpose(),\n",
    "        A.OneOf([\n",
    "            A.IAAAdditiveGaussianNoise(),\n",
    "            A.GaussNoise(),\n",
    "        ], p=0.2),\n",
    "        A.OneOf([\n",
    "            A.MotionBlur(p=.2),\n",
    "            A.MedianBlur(blur_limit=3, p=0.1),\n",
    "            A.Blur(blur_limit=3, p=0.1),\n",
    "        ], p=0.2),\n",
    "#         A.ShiftScaleRotate(shift_limit=0.0625, scale_limit=0.2, rotate_limit=0, p=0.2),\n",
    "#         A.OneOf([\n",
    "#             A.OpticalDistortion(p=0.3),\n",
    "#             A.GridDistortion(p=.1),\n",
    "#             A.IAAPiecewiseAffine(p=0.3),\n",
    "#         ], p=0.2),\n",
    "        A.OneOf([\n",
    "            A.CLAHE(clip_limit=2),\n",
    "            A.IAASharpen(),\n",
    "            A.IAAEmboss(),\n",
    "            A.RandomBrightnessContrast(),            \n",
    "        ], p=0.3),\n",
    "        A.HueSaturationValue(p=0.3),\n",
    "    ])\n",
    "\n",
    "val_transform = A.Compose([\n",
    "        A.Rotate(limit=180),\n",
    "        A.Flip(),\n",
    "#         A.ToGray(0.2),\n",
    "    ])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Dataset define and process"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_gen = TFClassificationDataGenerator(train_files=train_files,\n",
    "                                       val_files=val_files,\n",
    "                                       num_classes=NUM_CLASSES,\n",
    "                                       train_size=TRAIN_DS_SIZE,\n",
    "                                       val_size=VAL_DS_SIZE,\n",
    "                                       train_aug=None,\n",
    "                                       val_aug=None,\n",
    "                                       repeatds=False\n",
    "                                      )\n",
    "\n",
    "train_gen = df_gen.train_generator(TRAIN_DS_SIZE)\n",
    "val_gen = df_gen.validation_generator(VAL_DS_SIZE)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "# train_dataset_mem = []\n",
    "# for x, y in train_gen:\n",
    "# #             x, y = next(iter(ds))\n",
    "#     x1 = tf.squeeze(x)\n",
    "#     y1 = tf.squeeze(y)\n",
    "#     train_dataset_mem.append((x1, y1))\n",
    "    \n",
    "val_dataset_mem = []\n",
    "for x, y in val_gen:\n",
    "#             x, y = next(iter(ds))\n",
    "    x1 = tf.squeeze(x)\n",
    "    y1 = tf.squeeze(y)\n",
    "    val_dataset_mem.append((x1, y1))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_data_generator(ds, n_batch):\n",
    "    \"\"\"Get a generator returning n_batches random data of batch_size with n_features.\"\"\"\n",
    "\n",
    "    def data_generator():\n",
    "        for x, y in ds:\n",
    "#             x, y = next(iter(ds))\n",
    "#             x1 = tf.squeeze(x)\n",
    "#             y1 = tf.squeeze(y)\n",
    "            yield x, y\n",
    "\n",
    "    return data_generator\n",
    "\n",
    "# train_dataset = tf.data.Dataset.from_generator(\n",
    "#     get_data_generator(train_dataset_mem,TRAIN_DS_SIZE),\n",
    "#     output_types=(tf.float32, tf.uint8),\n",
    "#     output_shapes=(IMAGE_SIZE + NUM_CHANNELS, (NUM_CLASSES,)),\n",
    "# ).batch(BATCH_SIZE)\n",
    "val_dataset = tf.data.Dataset.from_generator(\n",
    "    get_data_generator(val_dataset_mem, VAL_DS_SIZE),\n",
    "    output_types=(tf.float32, tf.uint8),\n",
    "    output_shapes=(IMAGE_SIZE + NUM_CHANNELS, (NUM_CLASSES,)),\n",
    ").batch(BATCH_SIZE)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Train Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "class ClearTrialCheckpoints(tf.keras.callbacks.Callback):\n",
    "    def on_train_end(*args, **kwargs):\n",
    "        dir_to_look = os.path.join(MODEL_DIR, PROJECT_NAME)\n",
    "        dir_ls = [os.path.join(dir_to_look, d) for d in os.listdir(dir_to_look) if os.path.isdir(os.path.join(dir_to_look, d)) and 'trial' in d]\n",
    "        for d in dir_ls:\n",
    "            dir_of_concern = os.path.join(d, 'checkpoints')\n",
    "            if os.path.isdir(dir_of_concern):\n",
    "                print(dir_of_concern)\n",
    "                shutil.rmtree(dir_of_concern)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "callbacks = [EarlyStopping(patience=3),\n",
    "            ReduceLROnPlateau(patience=1),\n",
    "             ClearTrialCheckpoints(),\n",
    "            ]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Search: Running Trial #1\n",
      "\n",
      "Hyperparameter    |Value             |Best Value So Far \n",
      "optimizer         |adam              |?                 \n",
      "custom_resnet_b...|False             |?                 \n",
      "custom_resnet_b...|0                 |?                 \n",
      "custom_resnet_b...|1.4               |?                 \n",
      "custom_global_p...|1                 |?                 \n",
      "classification_...|0                 |?                 \n",
      "learning_rate     |0.001             |?                 \n",
      "\n",
      "Epoch 1/10\n",
      "      8/Unknown - 13s 2s/step - loss: 0.7858 - accuracy: 0.5000"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-11-2066427a1172>\", line 2, in <module>\n",
      "    auto_model.fit(val_dataset, batch_size=None, epochs=EPOCHS, callbacks=callbacks)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/autokeras/auto_model.py\", line 275, in fit\n",
      "    **kwargs\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/autokeras/engine/tuner.py\", line 173, in search\n",
      "    super().search(epochs=epochs, callbacks=new_callbacks, **fit_kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/kerastuner/engine/base_tuner.py\", line 131, in search\n",
      "    self.run_trial(trial, *fit_args, **fit_kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/kerastuner/engine/tuner.py\", line 155, in run_trial\n",
      "    model.fit(*fit_args, **copied_fit_kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 108, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 1098, in fit\n",
      "    tmp_logs = train_function(iterator)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py\", line 807, in _call\n",
      "    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 1848, in _filtered_call\n",
      "    cancellation_manager=cancellation_manager)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 1924, in _call_flat\n",
      "    ctx, args, cancellation_manager=cancellation_manager))\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 550, in call\n",
      "    ctx=ctx)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/execute.py\", line 60, in quick_execute\n",
      "    inputs, attrs, num_outputs)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 742, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/posixpath.py\", line 395, in realpath\n",
      "    path, ok = _joinrealpath(filename[:0], filename, {})\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/posixpath.py\", line 429, in _joinrealpath\n",
      "    if not islink(newpath):\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/posixpath.py\", line 171, in islink\n",
      "    st = os.lstat(path)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-11-2066427a1172>\", line 2, in <module>\n",
      "    auto_model.fit(val_dataset, batch_size=None, epochs=EPOCHS, callbacks=callbacks)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/autokeras/auto_model.py\", line 275, in fit\n",
      "    **kwargs\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/autokeras/engine/tuner.py\", line 173, in search\n",
      "    super().search(epochs=epochs, callbacks=new_callbacks, **fit_kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/kerastuner/engine/base_tuner.py\", line 131, in search\n",
      "    self.run_trial(trial, *fit_args, **fit_kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/kerastuner/engine/tuner.py\", line 155, in run_trial\n",
      "    model.fit(*fit_args, **copied_fit_kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 108, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 1098, in fit\n",
      "    tmp_logs = train_function(iterator)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py\", line 807, in _call\n",
      "    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 1848, in _filtered_call\n",
      "    cancellation_manager=cancellation_manager)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 1924, in _call_flat\n",
      "    ctx, args, cancellation_manager=cancellation_manager))\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 550, in call\n",
      "    ctx=ctx)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/execute.py\", line 60, in quick_execute\n",
      "    inputs, attrs, num_outputs)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3337, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3434, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 739, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/posixpath.py\", line 385, in abspath\n",
      "    return normpath(path)\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/posixpath.py\", line 353, in normpath\n",
      "    initial_slashes = path.startswith(sep)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-11-2066427a1172>\", line 2, in <module>\n",
      "    auto_model.fit(val_dataset, batch_size=None, epochs=EPOCHS, callbacks=callbacks)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/autokeras/auto_model.py\", line 275, in fit\n",
      "    **kwargs\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/autokeras/engine/tuner.py\", line 173, in search\n",
      "    super().search(epochs=epochs, callbacks=new_callbacks, **fit_kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/kerastuner/engine/base_tuner.py\", line 131, in search\n",
      "    self.run_trial(trial, *fit_args, **fit_kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/kerastuner/engine/tuner.py\", line 155, in run_trial\n",
      "    model.fit(*fit_args, **copied_fit_kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 108, in _method_wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 1098, in fit\n",
      "    tmp_logs = train_function(iterator)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py\", line 780, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py\", line 807, in _call\n",
      "    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 2829, in __call__\n",
      "    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 1848, in _filtered_call\n",
      "    cancellation_manager=cancellation_manager)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 1924, in _call_flat\n",
      "    ctx, args, cancellation_manager=cancellation_manager))\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 550, in call\n",
      "    ctx=ctx)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/tensorflow/python/eager/execute.py\", line 60, in quick_execute\n",
      "    inputs, attrs, num_outputs)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3337, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3434, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2922, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3146, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3356, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/sahil/.local/share/virtualenvs/network_search-ZkVDDU0n/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/inspect.py\", line 742, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/posixpath.py\", line 395, in realpath\n",
      "    path, ok = _joinrealpath(filename[:0], filename, {})\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/posixpath.py\", line 428, in _joinrealpath\n",
      "    newpath = join(path, name)\n",
      "  File \"/home/sahil/.pyenv/versions/3.7.9/lib/python3.7/posixpath.py\", line 86, in join\n",
      "    for b in map(os.fspath, p):\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "# auto_model.fit(train_dataset, validation_data=val_dataset, batch_size=None, epochs=EPOCHS, callbacks=callbacks)\n",
    "auto_model.fit(val_dataset, batch_size=None, epochs=EPOCHS, callbacks=callbacks)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Show Model "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "model = auto_model.export_model()\n",
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "auto_model.tuner.results_summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "dict(auto_model.tuner.get_best_hyperparameters(num_trials=1)[0])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
